version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "80:80"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 80 