version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"  # Host port : Container port
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PORT=8000
    volumes:
      - .:/app  # Useful for local development
    # No need to override the command since it's defined in the Dockerfile