version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "80:80"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - .:/app
    command: hypercorn main:app --bind 0.0.0.0:80 