version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"  # Host port : Container port
    environment:
      - PORT=${PORT}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - .:/app
    command: hypercorn main:app --bind 0.0.0.0:8000 